version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: sky-packets/portal:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./web/branding/sky_packets:/app/web/branding/sky_packets:ro
    command: ["/app/web/entrypoint.sh"]

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  db_data:

