# Generated by Django 5.1.1 on 2025-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="secret_salt",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
