# Generated by Django 5.1.1 on 2025-10-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tenant_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'site_id', 'date'], name='agg_tsd_idx')],
                'unique_together': {('date', 'tenant_id', 'site_id')},
            },
        ),
    ]
