# Generated by Django 5.1.1 on 2025-10-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('core', '0002_tenant_secret_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('splash_view', 'Splash View'), ('session_start', 'Session Start')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'site', 'type', 'ts'], name='event_tst_idx'),
        ),
    ]
