# Generated by Django 5.1.1 on 2025-10-11 01:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rev', models.CharField(max_length=64)),
                ('html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('js', models.TextField(blank=True, default='')),
                ('blocks_json', models.JSONField(blank=True, default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contentmgmt.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
